config/routes.rb
Temp::Application.routes.draw do
  
  resources :zipcodes do
    collection do 
      post 'get_details_by_zip'
      post 'get_state_by_zip'
    end 
  end 

   root :to => 'zipcodes#index'

end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
  attr_accessible :zip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zipcodes_controller.rb
class ZipcodesController < ApplicationController
  def index
    @zipcode=Zipcode.new
  end

  def get_details_by_zip 
    #this is REST webservice using JSON
    request = HTTPI::Request.new("http://free.worldweatheronline.com/feed/weather.ashx?q=#{params[:code]}&format=json&num_of_days=5&key=099493171a111943132302")
    response=HTTPI.get(request)
    #above two lines for getting json to the given url
    raw_body=response.raw_body
    result=ActiveSupport::JSON.decode(raw_body)
    data=result["data"]
    current_condition=data.assoc("current_condition")
    @current_report=current_condition[1][0]
    conditions=data.assoc("weather")
    @day1_report=conditions[1][0]
    @day2_report=conditions[1][1]
    @day3_report=conditions[1][2]
    
  end
  
  def get_state_by_zip
    #this is SOAP webservice using on XML
    client = Savon.client(wsdl: "http://www.webservicex.net/uszip.asmx?WSDL")
    response = client.call :get_info_by_zip, message: { "USZip" => params[:code] }
    info=response.to_array(:get_info_by_zip_response, :get_info_by_zip_result, :new_data_set, :table).first
    @state = info[:state]
    @city = info[:city]
    @area_code = info[:area_code]
    @time_zone = info[:time_zone]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Temp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zipcodes/_get_details_by_zip.html.erb
<h3>Weather Report</h3>
<hr/>
<div class="row">
  <div class="span1"></div>
  <div class="span3">
    <h5 class="text-info">Present Condition:</h5>
    <hr/>
    <b>Temp C :</b>
    <%= @current_report["temp_C"] %>&deg;</br>
    <b>Temp F :</b>
    <%= @current_report["temp_F"] %>&deg;</br>
    <b>Cloud Cover:</b>
    <%= @current_report["cloudcover"] %></br>
    <b>Humidity:</b>
    <%= @current_report["humidity"] %></br> 
    <b>Observation Time:</b>
    <%=@current_report["observation_time"] %></br> 
    <b>Pressure:</b> 
    <%= @current_report["pressure"] %></br>
    <hr/>
    <h5 class="text-info">Today</h5>
    <b>Date:</b>
    <%= @day1_report["date"]%> </br>
    <b>Max Temperature:</b>
    <%= @day1_report["tempMaxC"] %>&deg;C</br>
    <b>Minimum Temperature:</b>
    <%= @day1_report["tempMinC"] %>&deg;C</br>
  </div>
  <div class="span4">
    </br></br>
    </br>
    <h5 class="text-info">Tomorrow</h5>
    <b>Date:</b>
    <%= @day2_report["date"]%> </br>
    <b>Max Temperature:</b>
    <%= @day2_report["tempMaxC"]%>&deg;C</br>
    <b>Minimum Temperature:</b>
    <%= @day2_report["tempMinC"] %>&deg;C</br></br></br>
    <hr/>
    <h5 class="text-info">Day After Tomorrow</h5>
    <b>Date:</b>
    <%= @day3_report["date"]%> </br>
    <b>Max Temperature:</b>
    <%= @day3_report["tempMaxC"]%>&deg;C</br>
    <b>Minimum Temperature:</b>
    <%= @day3_report["tempMinC"] %>&deg;C</br>
  </div>
</div>

<%= @a %>

app/views/zipcodes/_get_state_by_zip.html.erb
<h3>Information about zipcode</h3>
<hr/>
<b>State:</b>
<%= @state %></br>
<b>City:</b>
<%= @city %></br>
<b>Area Code:</b>
<%= @area_code %></br>
<b>Time Zone :</b>
<%= @time_zone %>

app/views/zipcodes/get_details_by_zip.js.erb
$("#zipresults").html("<%= escape_javascript(render("get_details_by_zip")) %>");

app/views/zipcodes/get_state_by_zip.js.erb
$("#state_results").html("<%= escape_javascript(render("get_state_by_zip")) %>");

app/views/zipcodes/index.html.erb
<h3 class="text-success">Weather Report</h3>
<hr/>
<div class="row-fluid"">
  <div class="span1"></div>
  <div class="span5">
    <h4>Please Enter Your ZipCode:</h4>
    <%= form_tag get_details_by_zip_zipcodes_path, :id=>"weather", :remote => true do  %>
      <%= text_field_tag "code", "", :id=>"zip1"%></br>
      <%= submit_tag "search", :class=>"btn btn-success", :id=>"weather-report" %>
    <% end %>
  </div>
  <div class="span4">
    <%= form_tag get_state_by_zip_zipcodes_path, :id=>"ZipInfo", :remote => true do  %>
      <%= hidden_field_tag "code", "", :id=>"zip2"%></br>
      <% submit_tag "search", :class=>"btn btn-success" %>
    <% end %>
    
  </div>
 </div>
<hr/>
<div class="row-fluid">
<div id="zipresults" class="span8"></div>
<div id="state_results" class="span4"></div>
</div>

<script>
  // this script for submitting second "ZipInfo" form 
  // with the value of "Weather" form text_field_tag value
  $('#weather-report').click(function() {
   var val = $('#zip1').val();
   $("#zip2").val(val);
  $('#ZipInfo').submit();
});
</script>